### ISSUE TITLE
How to find the paper index

### ISSUE THREAD

**Issue by ZhuangLii** [mlresearch/v101#3]
Dear Sir,
My paper, named "Multi-branch siamese network for high performance online visual tracking", had been accepted by ACML 2019. However, I can't find the paper index in EI or SCI. Please provide me a solution to  find the index, thanks a lot.
Best wishes,
Zhuang

**Comment by lawrennd** [comment]
Hi Zhuang, I think that 's an issue with the indices rather than PMLR. They have their own stipulations and processes.
